# Generated by Django 4.1.7 on 2023-03-10 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.projectmodel')),
            ],
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='tag',
            field=models.ManyToManyField(related_name='project_tag', related_query_name='project_tag', to='todo.tagmodel'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.taskmodel'),
        ),
    ]
