# Generated by Django 4.1.7 on 2023-03-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_tag', related_query_name='project_tag', to='todo.tagmodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.taskmodel'),
        ),
    ]
