# Generated by Django 4.1.7 on 2023-03-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_projectmodel_tag_alter_projectmodel_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='task',
        ),
    ]
